### ISSUE TITLE
About Us Page Personal Descriptions

### ISSUE THREAD

**Issue by marco-zangari** [nothingnessbird/cfstudybuddies#66]
Write a sentence about yourself, y'all.

**Comment by nothingnessbird** [comment]
Kinley

They hold divers passions: from wilderness to technology and science, to rationality and effective altruism and psychology, and much more.

**Comment by Playingtygre** [comment]
Tiger is a born and raise from Indiana.

 He has traveled much of the world his younger years and likes to do the "hokey pokey",
 because that's what's it all about.

 During his spare Tiger never codes and can be found purchasing random things from Amazon,
 because he believes in supporting large corporations.

**Comment by stariel** [comment]
Ariel
~: Seattle, WA
A former research geneticist looking to transfer her problem solving skills to coding. Loves cats, knitting, the gym, and Scandinavian metal.

**Comment by Playingtygre** [comment]
~: Indy
Tiger enjoys performing the "hokey pokey", because that's what's it all about. During his spare time he never codes and can be found purchasing random things from Amazon.
